name: 'Glyphide'
version: '0.3.0'
main: 'org.winlogon.glyphide.GlyphideFormatter'
loader: 'org.winlogon.glyphide.GlyphideLoader'
description: 'A highly‑customizable chat‑formatting plugin for Paper Minecraft servers, powered by MiniMessage and placeholders for dynamic, colorful in‑game chat.'
folia-supported: true
api-version: 1.21
permissions:
  glyphide.admin:
    description: 'Ability to reload the configuration, and use MiniMessage formatting'
    default: op
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    ScalaLoader:
      load: BEFORE
      required: true
      join-classpath: true
