name: 'ChatFormatter'
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.ChatFormatter'
description: 'Simple chat formatter plugin'
folia-supported: true
api-version: 1.21
depend: ['LuckPerms']
permissions:
  chatformatter.admin:
    description: 'admin perms'
    default: op
commands:
  chatformatter:
    default: op
    aliases: ['cf', 'formatter']
